import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
      </Head>

      <main>
        <h1 >
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>


      </main>

      <footer >

      </footer>
    </div>
  )
}
